version: '3.8'

services:
  db:
    image: mysql:8.1
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    restart: always
    build: .
    working_dir: /bot
    volumes:
      - .:/bot
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
    depends_on:
      - db
    links:
      - db
    command: python main.py

volumes:
  db:
    driver: local

