version: '3.8'

services:
  mysql:
    hostname: mysql
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: 'swgoh'
      MYSQL_USER: 'swgoh'
      MYSQL_PASSWORD: 'swgoh'
      MYSQL_ROOT_PASSWORD: 'mauFJcuf5dhRMQrjj'
    expose: 
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      swgoh-network:
        aliases:
          - mysql

  bot:
    hostname: bot
    restart: always
    build: .
    environment:
      BOT_API_TOKEN: ${BOT_API_TOKEN}
    depends_on:
      - mysql
    networks: 
      - swgoh-network

volumes:
  db:
    driver: local

networks:
  swgoh-network:    
    driver: bridge
    name: swgoh-network
